### ISSUE TITLE
Add support for RISC-V

### ISSUE THREAD

**Issue by rwmjones** [eballetbo/unzboot#2]
I tried this tool and it doesn't work for RISC-V kernels.  I didn't try very hard to make it work, but there's a RISC-V kernel here that you can try out:

http://fedora.riscv.rocks/koji/buildinfo?buildID=252275

Running it on this kernel (after fixing the exit code problems):

```
$ ./unzboot /var/tmp/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64 vmlinuz.out
./unzboot: /var/tmp/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64: cannot find ARM64 compressed image
```

**Comment by eballetbo** [comment]
Hi @rwmjones, actually this tool only supports aarch64 kernels. What's the use case? Or why are you interested on add support for RISC-V?

**Comment by rwmjones** [comment]
AIUI RISC-V kernels also use the same compressed EFI wrapper and so this tool might be extended to support them.  However I don't know the precise details.

**Comment by eballetbo** [comment]
I don't think I have a test environment for that. From a very quick look, can you try if this works?
```
@@ -282,15 +284,23 @@ int main(int argc, char *argv[]) {
 
     /* check the arm64 magic header value -- very old kernels may not have it */
     if (size > ARM64_MAGIC_OFFSET + 4 &&
-        memcmp(buffer + ARM64_MAGIC_OFFSET, "ARM\x64", 4) == 0) {
-
+        (memcmp(buffer + ARM64_MAGIC_OFFSET, "ARM\x64", 4) == 0)) {
+        fprintf(stdout, "%s: found ARM64 header\n", argv[0]);
+        if (!g_file_set_contents(output_file, (char *)buffer, size, NULL)) {
+            g_free(buffer);
+            fprintf(stderr, "%s: cannot write to output file\n", argv[0]);
+            exit(EXIT_FAILURE);
+        }
+    } else if (size > ARM64_MAGIC_OFFSET + 4 &&
+        (memcmp(buffer + ARM64_MAGIC_OFFSET, "RSC\x05", 4) == 0)) {
+        fprintf(stdout, "%s: found RISC-V header\n", argv[0]);
         if (!g_file_set_contents(output_file, (char *)buffer, size, NULL)) {
             g_free(buffer);
             fprintf(stderr, "%s: cannot write to output file\n", argv[0]);
             exit(EXIT_FAILURE);
         }
     } else {
-        fprintf(stderr, "%s: %s: cannot find ARM64 compressed image\n", argv[0], input_file);
+        fprintf(stderr, "%s: %s: cannot find ARM64/RISC-V compressed image\n", argv[0], input_file);
         exit(EXIT_FAILURE);
     }
```

**Comment by rwmjones** [comment]
It "works" to the extent that it extracts something from the image:

```
$ ll /boot/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64 
-rwxr-xr-x 1 root root 14299648 Sep 21 01:00 /boot/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64
$ file /boot/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64 
/boot/vmlinuz-6.5.4-300.0.riscv64.fc39.riscv64: PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows, 2 sections
$ ll output 
-rw-r--r-- 1 rjones rjones 44306432 Jan 29 13:33 output
$ file output 
output: PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows, 2 sections
```

However qemu still can't boot the resulting output.  However that might be an issue with qemu for all I know.

BTW `fprintf(stdout)` is just `printf`.

**Comment by eballetbo** [comment]
file still thinks is a `PE32+ executable` so I don't think it went well. I guess, qemu is able to deal with Linux EFI zboot images, at least on aarch64, so maybe the proper way should be teach qemu to deal with these images on risc-v too. 
In any case, the tool should help if Risc-V uses the same Linux EFI zboot images as ARM64. I Will need to look in details, though. I'll try to investigate a bit more.

**Comment by aurel32** [comment]
Thanks for this patch, I have tried it successfully for a `vmlinuz.efi` binary using gzip compression (not the one from Fedora). The uncompressed file is indeed still a PE32+ executable also in my case. I believe it's because the kernel has been compiled with `CONFIG_EFI_STUB=y` and it is what is packed in the `vmlinuz.efi`. I don't know if it is on purpose or not, but it something that bootloaders accept.

**Comment by aurel32** [comment]
When I say it works, I mean I am able to boot the resulting kernel with `qemu-system-riscv64 -M virt -serial stdio -kernel vmlinux`

**Comment by eballetbo** [comment]
Hey, I forget about this, sorry about that. Do you expect anything else? or the test done by @aurel32 is enough to close the issue?
